import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: "#eef4f1",
  },
  topNav: {
    minHeight: 92,
    backgroundColor: "#082f49",
    borderBottomWidth: 1,
    borderBottomColor: "#134e4a",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 18,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  navGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    flexShrink: 1,
    minWidth: 0,
    maxWidth: "100%",
  },
  navGroupDate: {
    flexShrink: 0,
  },
  navCopy: {
    flexShrink: 1,
    minWidth: 0,
  },
  navIcon: {
    width: 54,
    height: 54,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(217, 249, 157, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(217, 249, 157, 0.26)",
  },
  navLabel: {
    color: "#a7f3d0",
    fontSize: 16,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  navTitle: {
    color: "#f8fafc",
    fontSize: 29,
    lineHeight: 35,
    fontWeight: "900",
    flexShrink: 1,
  },
  screen: {
    flex: 1,
    padding: 16,
  },
  homeLayout: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#d7e4df",
    alignItems: "center",
    justifyContent: "center",
    gap: 44,
    padding: 20,
  },
  homeCopy: {
    alignItems: "center",
    gap: 12,
  },
  heroIcon: {
    width: 148,
    height: 148,
    borderRadius: 8,
    backgroundColor: "#ccfbf1",
    borderWidth: 1,
    borderColor: "#99f6e4",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  homeTitle: {
    color: "#0f172a",
    fontSize: 46,
    lineHeight: 54,
    fontWeight: "900",
    textAlign: "center",
  },
  homeSubtitle: {
    color: "#475569",
    fontSize: 22,
    lineHeight: 30,
    fontWeight: "700",
    textAlign: "center",
  },
  button: {
    width: "100%",
    maxWidth: 340,
    minHeight: 88,
    borderRadius: 8,
    backgroundColor: "#0f766e",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    paddingHorizontal: 22,
    borderWidth: 1,
    borderColor: "#0d9488",
  },
  secondaryButton: {
    backgroundColor: "#ffffff",
    borderColor: "#cbd5e1",
  },
  buttonPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.99 }],
  },
  buttonText: {
    color: "#ecfeff",
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "900",
    flexShrink: 1,
    textAlign: "center",
  },
  secondaryButtonText: {
    color: "#0f172a",
  },
  noticeLayout: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#d7e4df",
    alignItems: "center",
    justifyContent: "center",
    gap: 22,
    padding: 20,
  },
  noticeIcon: {
    width: 132,
    height: 132,
    borderRadius: 8,
    backgroundColor: "#ccfbf1",
    alignItems: "center",
    justifyContent: "center",
  },
  errorNoticeIcon: {
    backgroundColor: "#fee2e2",
  },
  noticeTitle: {
    color: "#0f172a",
    fontSize: 38,
    lineHeight: 46,
    fontWeight: "900",
    textAlign: "center",
  },
  noticeText: {
    color: "#475569",
    fontSize: 24,
    lineHeight: 32,
    fontWeight: "700",
    textAlign: "center",
    maxWidth: 760,
  },
  scanLayout: {
    flex: 1,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#020617",
    borderWidth: 1,
    borderColor: "#134e4a",
  },
  camera: {
    ...StyleSheet.absoluteFill,
  },
  cameraShade: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(2, 6, 23, 0.3)",
    pointerEvents: "none",
  },
  scanOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
    gap: 22,
    padding: 18,
    pointerEvents: "none",
  },
  scanHeader: {
    minHeight: 58,
    maxWidth: "100%",
    borderRadius: 8,
    backgroundColor: "rgba(8, 47, 73, 0.88)",
    borderWidth: 1,
    borderColor: "rgba(236, 254, 255, 0.2)",
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingHorizontal: 24,
  },
  scanStatusDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#22c55e",
  },
  scanStatus: {
    color: "#ecfeff",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "900",
    flexShrink: 1,
  },
  scanFrame: {
    width: "72%",
    maxWidth: 520,
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(236, 254, 255, 0.25)",
    backgroundColor: "rgba(15, 118, 110, 0.12)",
  },
  corner: {
    position: "absolute",
    width: 74,
    height: 74,
    borderColor: "#d9f99d",
  },
  cornerTopLeft: {
    left: -2,
    top: -2,
    borderTopWidth: 9,
    borderLeftWidth: 9,
  },
  cornerTopRight: {
    right: -2,
    top: -2,
    borderTopWidth: 9,
    borderRightWidth: 9,
  },
  cornerBottomLeft: {
    left: -2,
    bottom: -2,
    borderBottomWidth: 9,
    borderLeftWidth: 9,
  },
  cornerBottomRight: {
    right: -2,
    bottom: -2,
    borderBottomWidth: 9,
    borderRightWidth: 9,
  },
  scanInstruction: {
    color: "#f8fafc",
    fontSize: 30,
    lineHeight: 38,
    fontWeight: "900",
    textAlign: "center",
  },
  scanActions: {
    position: "absolute",
    left: 18,
    right: 18,
    bottom: 18,
    alignItems: "center",
  },
  resultLayout: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 24,
    padding: 20,
  },
  validResult: {
    backgroundColor: "#f0fdf4",
    borderColor: "#86efac",
  },
  invalidResult: {
    backgroundColor: "#fef2f2",
    borderColor: "#fca5a5",
  },
  resultIcon: {
    width: 174,
    height: 174,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    borderWidth: 1,
  },
  validIcon: {
    borderColor: "#86efac",
  },
  invalidIcon: {
    borderColor: "#fca5a5",
  },
  resultCopy: {
    alignItems: "center",
    gap: 8,
  },
  resultTitle: {
    fontSize: 48,
    lineHeight: 56,
    fontWeight: "900",
    textAlign: "center",
  },
  validText: {
    color: "#15803d",
  },
  invalidText: {
    color: "#b91c1c",
  },
  resultSubtitle: {
    color: "#0f172a",
    fontSize: 30,
    lineHeight: 38,
    fontWeight: "900",
    textAlign: "center",
  },
  routeText: {
    color: "#334155",
    fontSize: 24,
    lineHeight: 32,
    fontWeight: "800",
    textAlign: "center",
  },
});
