import { StyleSheet } from "react-native";

const colors = {
  ink: "#202126",
  muted: "#777c82",
  faint: "#a8adb2",
  rail: "#0d0f0f",
  railDivider: "#272b2b",
  orange: "#ff7148",
  red: "#f14136",
  redDark: "#d93b32",
  cream: "#fff8f4",
  paper: "#ffffff",
  page: "#f7f7f5",
  divider: "#e5e7eb",
  softDivider: "#f0f1f2",
  green: "#0fbd77",
};

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: colors.page,
  },
  systemRail: {
    minHeight: 25,
    backgroundColor: colors.rail,
    borderBottomWidth: 1,
    borderBottomColor: colors.railDivider,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 4,
  },
  statusItem: {
    minHeight: 15,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRightWidth: 1,
    borderRightColor: colors.railDivider,
    paddingRight: 10,
  },
  statusDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.green,
  },
  statusLabel: {
    color: "#8d9391",
    fontSize: 9,
    lineHeight: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  statusValue: {
    color: "#c7cdca",
    fontSize: 9,
    lineHeight: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  topNav: {
    minHeight: 90,
    backgroundColor: colors.orange,
    borderBottomWidth: 1,
    borderBottomColor: colors.redDark,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    paddingHorizontal: 28,
    paddingVertical: 16,
  },
  topNavCompact: {
    minHeight: 166,
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "center",
    gap: 10,
    paddingHorizontal: 26,
    paddingTop: 4,
    paddingBottom: 18,
  },
  compactMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
  },
  brandBlock: {
    minWidth: 92,
    alignItems: "center",
    gap: 4,
  },
  brandLogo: {
    width: 80,
    height: 50,
  },
  brandText: {
    color: colors.cream,
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "900",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  stationBlock: {
    flex: 1,
    alignItems: "center",
    gap: 5,
    minWidth: 0,
  },
  stationBlockCompact: {
    flex: 0,
    width: "100%",
  },
  stationTitleRow: {
    maxWidth: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
  },
  navLabel: {
    color: "#ffe5dc",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  navTitle: {
    color: "#fffdfa",
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "900",
    textAlign: "center",
    textTransform: "uppercase",
    flexShrink: 1,
  },
  navTitleCompact: {
    fontSize: 20,
    lineHeight: 25,
  },
  logoBlock: {
    minWidth: 112,
    alignItems: "flex-end",
    gap: 10,
  },
  logoBadge: {
    width: 106,
    height: 44,
    borderRadius: 8,
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.55)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    paddingVertical: 5,
    overflow: "hidden",
  },
  logoImage: {
    width: "100%",
    height: "100%",
    borderRadius: 6,
  },
  dateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    maxWidth: 160,
  },
  navDate: {
    color: "#fff1ec",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "900",
  },
  screen: {
    flex: 1,
    padding: 16,
    backgroundColor: colors.paper,
  },
  homeLayout: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.divider,
    alignItems: "center",
    justifyContent: "center",
    gap: 38,
    padding: 20,
    boxShadow: "0 8px 18px rgba(0, 0, 0, 0.06)",
    elevation: 2,
  },
  homeCopy: {
    alignItems: "center",
    gap: 12,
  },
  heroIcon: {
    width: 148,
    height: 148,
    borderRadius: 8,
    backgroundColor: "#fff1ec",
    borderWidth: 1,
    borderColor: "#ffd6ca",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  homeTitle: {
    color: colors.ink,
    fontSize: 44,
    lineHeight: 52,
    fontWeight: "900",
    textAlign: "center",
    textTransform: "uppercase",
  },
  homeSubtitle: {
    color: colors.muted,
    fontSize: 20,
    lineHeight: 28,
    fontWeight: "800",
    textAlign: "center",
  },
  button: {
    width: "100%",
    maxWidth: 340,
    minHeight: 50,
    borderRadius: 8,
    backgroundColor: colors.red,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: "#f26349",
  },
  scanNowButton: {
    backgroundColor: colors.orange,
    borderColor: colors.redDark,
  },
  secondaryButton: {
    backgroundColor: colors.paper,
    borderColor: colors.divider,
  },
  buttonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  buttonText: {
    color: "#fff8f4",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
    flexShrink: 1,
    textAlign: "center",
    textTransform: "uppercase",
  },
  secondaryButtonText: {
    color: colors.ink,
  },
  noticeLayout: {
    flex: 1,
    margin: 16,
    borderRadius: 8,
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.divider,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "flex-start",
    boxShadow: "0 8px 18px rgba(0, 0, 0, 0.06)",
    elevation: 2,
  },
  errorNoticeLayout: {
    borderColor: "#f7bfba",
  },
  noticeAccent: {
    width: "100%",
    height: 6,
    backgroundColor: colors.orange,
    borderBottomWidth: 1,
    borderBottomColor: "#ffd6ca",
  },
  errorNoticeAccent: {
    backgroundColor: colors.red,
    borderBottomColor: "#fec8c4",
  },
  noticeBody: {
    flex: 1,
    width: "100%",
    maxWidth: 560,
    alignItems: "center",
    justifyContent: "center",
    gap: 18,
    paddingHorizontal: 24,
    paddingVertical: 30,
  },
  noticeIcon: {
    width: 82,
    height: 82,
    borderRadius: 8,
    backgroundColor: "#fff1ec",
    borderWidth: 1,
    borderColor: "#ffd6ca",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 2,
  },
  errorNoticeIcon: {
    backgroundColor: "#fff1f0",
    borderColor: "#fec8c4",
  },
  noticeCopy: {
    width: "100%",
    alignItems: "center",
    gap: 9,
  },
  noticeTitle: {
    color: colors.ink,
    fontSize: 31,
    lineHeight: 38,
    fontWeight: "900",
    textAlign: "center",
    flexShrink: 1,
  },
  noticeText: {
    color: colors.muted,
    fontSize: 17,
    lineHeight: 25,
    fontWeight: "700",
    textAlign: "center",
    maxWidth: 520,
    flexShrink: 1,
  },
  noticeAction: {
    width: "100%",
    alignItems: "center",
    marginTop: 2,
  },
  scanLayout: {
    flex: 1,
    margin: 16,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: colors.rail,
    borderWidth: 1,
    borderColor: "#2c2e31",
  },
  camera: {
    ...StyleSheet.absoluteFill,
  },
  cameraShade: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(13, 15, 15, 0.42)",
    pointerEvents: "none",
  },
  scanOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
    gap: 22,
    padding: 18,
    pointerEvents: "none",
  },
  scanHeader: {
    minHeight: 50,
    maxWidth: "100%",
    borderRadius: 8,
    backgroundColor: "rgba(255, 113, 72, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(255, 248, 244, 0.26)",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 22,
  },
  scanStatusDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.green,
  },
  scanStatus: {
    color: "#fffdfa",
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "900",
    flexShrink: 1,
    textTransform: "uppercase",
  },
  scanFrame: {
    width: "72%",
    maxWidth: 500,
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(255, 248, 244, 0.3)",
    backgroundColor: "rgba(255, 113, 72, 0.1)",
  },
  corner: {
    position: "absolute",
    width: 68,
    height: 68,
    borderColor: colors.orange,
  },
  cornerTopLeft: {
    left: -2,
    top: -2,
    borderTopWidth: 8,
    borderLeftWidth: 8,
  },
  cornerTopRight: {
    right: -2,
    top: -2,
    borderTopWidth: 8,
    borderRightWidth: 8,
  },
  cornerBottomLeft: {
    left: -2,
    bottom: -2,
    borderBottomWidth: 8,
    borderLeftWidth: 8,
  },
  cornerBottomRight: {
    right: -2,
    bottom: -2,
    borderBottomWidth: 8,
    borderRightWidth: 8,
  },
  scanInstruction: {
    color: "#fffdfa",
    fontSize: 24,
    lineHeight: 31,
    fontWeight: "900",
    textAlign: "center",
    textTransform: "uppercase",
  },
  scanActions: {
    position: "absolute",
    left: 18,
    right: 18,
    bottom: 18,
    alignItems: "center",
  },
  resultLayout: {
    flex: 1,
    margin: 16,
    borderRadius: 8,
    borderWidth: 1,
    backgroundColor: colors.paper,
    alignItems: "center",
    justifyContent: "center",
    gap: 20,
    paddingHorizontal: 22,
    paddingVertical: 26,
    boxShadow: "0 8px 18px rgba(0, 0, 0, 0.06)",
    elevation: 2,
  },
  enterResult: {
    borderColor: "#bfead7",
  },
  exitResult: {
    borderColor: "#ffd7a8",
  },
  invalidResult: {
    borderColor: "#f7bfba",
  },
  resultNoticeRow: {
    width: "100%",
    maxWidth: 620,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 24,
  },
  resultIcon: {
    width: 146,
    height: 146,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  resultCopy: {
    flex: 1,
    minWidth: 0,
    alignItems: "center",
    gap: 4,
  },
  resultTitle: {
    fontSize: 38,
    lineHeight: 45,
    fontWeight: "900",
    textAlign: "center",
    flexShrink: 1,
  },
  resultMessage: {
    fontSize: 34,
    lineHeight: 41,
    fontWeight: "900",
    textAlign: "center",
    flexShrink: 1,
  },
  enterResultText: {
    color: "#158052",
  },
  exitResultText: {
    color: "#df8a13",
  },
  invalidResultText: {
    color: colors.redDark,
  },
  resultRetryText: {
    color: colors.faint,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    textAlign: "center",
    textTransform: "uppercase",
  },
});
