import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: "#eef4f1",
  },
  topNav: {
    minHeight: 92,
    backgroundColor: "#082f49",
    borderBottomWidth: 1,
    borderBottomColor: "#134e4a",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 38,
    paddingVertical: 18,
  },
  navGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    minWidth: 260,
  },
  navIcon: {
    width: 54,
    height: 54,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(217, 249, 157, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(217, 249, 157, 0.26)",
  },
  navLabel: {
    color: "#a7f3d0",
    fontSize: 16,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  navTitle: {
    color: "#f8fafc",
    fontSize: 29,
    lineHeight: 35,
    fontWeight: "900",
  },
  screen: {
    flex: 1,
    padding: 30,
  },
  homeLayout: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#d7e4df",
    alignItems: "center",
    justifyContent: "center",
    gap: 44,
    padding: 36,
  },
  homeCopy: {
    alignItems: "center",
    gap: 12,
  },
  heroIcon: {
    width: 148,
    height: 148,
    borderRadius: 8,
    backgroundColor: "#ccfbf1",
    borderWidth: 1,
    borderColor: "#99f6e4",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  homeTitle: {
    color: "#0f172a",
    fontSize: 58,
    lineHeight: 66,
    fontWeight: "900",
    textAlign: "center",
  },
  homeSubtitle: {
    color: "#475569",
    fontSize: 25,
    lineHeight: 32,
    fontWeight: "700",
    textAlign: "center",
  },
  button: {
    minWidth: 300,
    minHeight: 88,
    borderRadius: 8,
    backgroundColor: "#0f766e",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    paddingHorizontal: 34,
    borderWidth: 1,
    borderColor: "#0d9488",
  },
  secondaryButton: {
    backgroundColor: "#ffffff",
    borderColor: "#cbd5e1",
  },
  buttonPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.99 }],
  },
  buttonText: {
    color: "#ecfeff",
    fontSize: 34,
    lineHeight: 40,
    fontWeight: "900",
  },
  secondaryButtonText: {
    color: "#0f172a",
  },
  noticeLayout: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#d7e4df",
    alignItems: "center",
    justifyContent: "center",
    gap: 22,
    padding: 36,
  },
  noticeIcon: {
    width: 132,
    height: 132,
    borderRadius: 8,
    backgroundColor: "#ccfbf1",
    alignItems: "center",
    justifyContent: "center",
  },
  errorNoticeIcon: {
    backgroundColor: "#fee2e2",
  },
  noticeTitle: {
    color: "#0f172a",
    fontSize: 46,
    lineHeight: 54,
    fontWeight: "900",
    textAlign: "center",
  },
  noticeText: {
    color: "#475569",
    fontSize: 24,
    lineHeight: 32,
    fontWeight: "700",
    textAlign: "center",
    maxWidth: 760,
  },
  scanLayout: {
    flex: 1,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#020617",
    borderWidth: 1,
    borderColor: "#134e4a",
  },
  camera: {
    ...StyleSheet.absoluteFill,
  },
  cameraShade: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(2, 6, 23, 0.3)",
    pointerEvents: "none",
  },
  scanOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
    gap: 22,
    padding: 30,
    pointerEvents: "none",
  },
  scanHeader: {
    minHeight: 58,
    borderRadius: 8,
    backgroundColor: "rgba(8, 47, 73, 0.88)",
    borderWidth: 1,
    borderColor: "rgba(236, 254, 255, 0.2)",
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingHorizontal: 24,
  },
  scanStatusDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#22c55e",
  },
  scanStatus: {
    color: "#ecfeff",
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "900",
  },
  scanFrame: {
    width: "48%",
    minWidth: 360,
    maxWidth: 520,
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(236, 254, 255, 0.25)",
    backgroundColor: "rgba(15, 118, 110, 0.12)",
  },
  corner: {
    position: "absolute",
    width: 74,
    height: 74,
    borderColor: "#d9f99d",
  },
  cornerTopLeft: {
    left: -2,
    top: -2,
    borderTopWidth: 9,
    borderLeftWidth: 9,
  },
  cornerTopRight: {
    right: -2,
    top: -2,
    borderTopWidth: 9,
    borderRightWidth: 9,
  },
  cornerBottomLeft: {
    left: -2,
    bottom: -2,
    borderBottomWidth: 9,
    borderLeftWidth: 9,
  },
  cornerBottomRight: {
    right: -2,
    bottom: -2,
    borderBottomWidth: 9,
    borderRightWidth: 9,
  },
  scanInstruction: {
    color: "#f8fafc",
    fontSize: 38,
    lineHeight: 46,
    fontWeight: "900",
    textAlign: "center",
  },
  scanActions: {
    position: "absolute",
    left: 30,
    right: 30,
    bottom: 30,
    alignItems: "center",
  },
  resultLayout: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 24,
    padding: 36,
  },
  validResult: {
    backgroundColor: "#f0fdf4",
    borderColor: "#86efac",
  },
  invalidResult: {
    backgroundColor: "#fef2f2",
    borderColor: "#fca5a5",
  },
  resultIcon: {
    width: 174,
    height: 174,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    borderWidth: 1,
  },
  validIcon: {
    borderColor: "#86efac",
  },
  invalidIcon: {
    borderColor: "#fca5a5",
  },
  resultCopy: {
    alignItems: "center",
    gap: 8,
  },
  resultTitle: {
    fontSize: 62,
    lineHeight: 70,
    fontWeight: "900",
    textAlign: "center",
  },
  validText: {
    color: "#15803d",
  },
  invalidText: {
    color: "#b91c1c",
  },
  resultSubtitle: {
    color: "#0f172a",
    fontSize: 36,
    lineHeight: 44,
    fontWeight: "900",
    textAlign: "center",
  },
  routeText: {
    color: "#334155",
    fontSize: 28,
    lineHeight: 36,
    fontWeight: "800",
    textAlign: "center",
  },
});
